symbols:
  # region models

  'ApimodelsXRayBulkTicketObservabilityRequest@py.sessionhistory.mod':
    id: 'ApimodelsXRayBulkTicketObservabilityRequest@py.sessionhistory.mod'
    name: 'ApimodelsXRayBulkTicketObservabilityRequest'
    type: 'model'
    fields:
      'ticket_observabilities':
        type: 'List[ApimodelsXRayTicketObservabilityRequest]'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/apimodels_x_ray_bulk_ticket_observability_request.py'
    example: |-
      apimodels_x_ray_bulk_ticket_observability_request = sessionhistory_models.ApimodelsXRayBulkTicketObservabilityRequest.create(...)

  'ApimodelsXRayBulkTicketObservabilityResponse@py.sessionhistory.mod':
    id: 'ApimodelsXRayBulkTicketObservabilityResponse@py.sessionhistory.mod'
    name: 'ApimodelsXRayBulkTicketObservabilityResponse'
    type: 'model'
    fields:
      'ticket_i_ds':
        type: 'List[str]'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/apimodels_x_ray_bulk_ticket_observability_response.py'
    example: |-
      apimodels_x_ray_bulk_ticket_observability_response = sessionhistory_models.ApimodelsXRayBulkTicketObservabilityResponse.create(...)

  'ApimodelsXRayTicketObservabilityRequest@py.sessionhistory.mod':
    id: 'ApimodelsXRayTicketObservabilityRequest@py.sessionhistory.mod'
    name: 'ApimodelsXRayTicketObservabilityRequest'
    type: 'model'
    fields:
      'action':
        type: 'str'
        required: true
      'game_mode':
        type: 'str'
        required: true
      'is_backfill_match':
        type: 'bool'
        required: true
      'is_rule_set_flexed':
        type: 'bool'
        required: true
      'namespace':
        type: 'str'
        required: true
      'session_tick_id':
        type: 'str'
        required: true
      'tick_id':
        type: 'int'
        required: true
      'ticket_id':
        type: 'str'
        required: true
      'timestamp':
        type: 'str'
        required: true
      'active_alliance_rule':
        type: 'ModelsAllianceRule'
        required: false
      'active_matching_rule':
        type: 'List[ModelsMatchingRule]'
        required: false
      'function':
        type: 'str'
        required: false
      'iteration':
        type: 'int'
        required: false
      'match_id':
        type: 'str'
        required: false
      'remaining_players_per_ticket':
        type: 'List[int]'
        required: false
      'remaining_tickets':
        type: 'int'
        required: false
      'time_to_match_sec':
        type: 'float'
        required: false
      'unbackfill_reason':
        type: 'str'
        required: false
      'unmatch_reason':
        type: 'str'
        required: false
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/apimodels_x_ray_ticket_observability_request.py'
    example: |-
      apimodels_x_ray_ticket_observability_request = sessionhistory_models.ApimodelsXRayTicketObservabilityRequest.create(...)

  'ApimodelsXRayTicketObservabilityResponse@py.sessionhistory.mod':
    id: 'ApimodelsXRayTicketObservabilityResponse@py.sessionhistory.mod'
    name: 'ApimodelsXRayTicketObservabilityResponse'
    type: 'model'
    fields:
      'ticket_id':
        type: 'str'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/apimodels_x_ray_ticket_observability_response.py'
    example: |-
      apimodels_x_ray_ticket_observability_response = sessionhistory_models.ApimodelsXRayTicketObservabilityResponse.create(...)

  'ModelsAllianceRule@py.sessionhistory.mod':
    id: 'ModelsAllianceRule@py.sessionhistory.mod'
    name: 'ModelsAllianceRule'
    type: 'model'
    fields:
      'max_number':
        type: 'int'
        required: true
      'min_number':
        type: 'int'
        required: true
      'player_max_number':
        type: 'int'
        required: true
      'player_min_number':
        type: 'int'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/models_alliance_rule.py'
    example: |-
      models_alliance_rule = sessionhistory_models.ModelsAllianceRule.create(...)

  'ModelsMatchingRule@py.sessionhistory.mod':
    id: 'ModelsMatchingRule@py.sessionhistory.mod'
    name: 'ModelsMatchingRule'
    type: 'model'
    fields:
      'attribute':
        type: 'str'
        required: true
      'criteria':
        type: 'str'
        required: true
      'reference':
        type: 'float'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/models_matching_rule.py'
    example: |-
      models_matching_rule = sessionhistory_models.ModelsMatchingRule.create(...)

  'ResponseError@py.sessionhistory.mod':
    id: 'ResponseError@py.sessionhistory.mod'
    name: 'ResponseError'
    type: 'model'
    fields:
      'attributes':
        type: 'Dict[str, str]'
        required: true
      'error_code':
        type: 'int'
        required: true
      'error_message':
        type: 'str'
        required: true
      'message':
        type: 'str'
        required: true
      'name':
        type: 'str'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/models/response_error.py'
    example: |-
      response_error = sessionhistory_models.ResponseError.create(...)

  # endregion models

  # region functions

  'create_xray_bulk_ticket_observability@py.sessionhistory.fun':
    id: 'create_xray_bulk_ticket_observability@py.sessionhistory.fun'
    name: 'create_xray_bulk_ticket_observability'
    type: 'function'
    description: |-
      Create bulk ticket observability request
      Request body details (all attributes are optional):
      Timestamp : timestamp when calling this endpoint
      Action : support one of the following value:
      1. "matchFound"
      2. "matchNotFound"
      3. "flexed"
      PartyID : ticket Party ID
      MatchID : match ID will be filled only when match found
      Namespace : ticket current namespace
      GameMode : ticket current matchpool
      ActiveAllianceRule : current active alliance ruleset
      ActiveMatchingRule : current active matching ruleset
      Function : name of the function that called the endpoint
      Iteration : total iteration before match found
      TimeToMatchSec : time to match (in seconds) will be filled only when match found
      UnmatchReason : reason when unable to find match
      RemainingTickets : remaining ticket when unable to find match
      RemainingPlayersPerTicket : remaining players when unable to find match
      UnbackfillReason : reason when unable to backfill
      IsBackfillMatch : flag to distinguish between new match and backfill match
      IsRuleSetFlexed : flag if ruleset is getting flexed
      TickID : tick id for the matchmaking tick
      SessionTickID : session tick id for differentiate session when doing matches
    arguments:
      'body':
        type: 'ApimodelsXRayBulkTicketObservabilityRequest'
        required: true
      'namespace':
        type: 'str'
        required: true
        description: |-
          namespace of the game
    return_type: 'Tuple[Union[None, ApimodelsXRayBulkTicketObservabilityResponse], Union[None, HttpResponse, ResponseError]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.sessionhistory as sessionhistory'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/operations/x_ray/create_xray_bulk_ticket_cacbf6.py'
    example: |-
      result, error = sessionhistory.create_xray_bulk_ticket_observability(...)
      if error:
          # handle_error(error)
    tags:
      - 'bulk'
      - 'create'
      - 'observability'
      - 'ray'
      - 'ticket'
      - 'x'
      - 'xray'

  'create_xray_ticket_observability@py.sessionhistory.fun':
    id: 'create_xray_ticket_observability@py.sessionhistory.fun'
    name: 'create_xray_ticket_observability'
    type: 'function'
    description: |-
      Create ticket observability request
      Request body details (all attributes are optional):
      Timestamp : timestamp when calling this endpoint
      Action : support one of the following value:
      1. "matchFound"
      2. "matchNotFound"
      3. "flexed"
      TicketID : ticket ID
      MatchID : match ID will be filled only when match found
      Namespace : ticket current namespace
      GameMode : ticket current matchpool
      ActiveAllianceRule : current active alliance ruleset
      ActiveMatchingRule : current active matching ruleset
      Function : name of the function that called the endpoint
      Iteration : total iteration before match found
      TimeToMatchSec : time to match (in seconds) will be filled only when match found
      UnmatchReason : reason when unable to find match
      RemainingTickets : remaining ticket when unable to find match
      RemainingPlayersPerTicket : remaining players when unable to find match
      UnbackfillReason : reason when unable to backfill
      IsBackfillMatch : flag to distinguish between new match and backfill match
      IsRuleSetFlexed : flag if ruleset is getting flexed
      TickID : tick id for the matchmaking tick
      SessionTickID : session tick id for differentiate session when doing matches
    arguments:
      'body':
        type: 'ApimodelsXRayTicketObservabilityRequest'
        required: true
      'namespace':
        type: 'str'
        required: true
        description: |-
          namespace of the game
    return_type: 'Tuple[Union[None, ApimodelsXRayTicketObservabilityResponse], Union[None, HttpResponse, ResponseError]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.sessionhistory as sessionhistory'
      - 'import accelbyte_py_sdk.api.sessionhistory.models as sessionhistory_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/sessionhistory/operations/x_ray/create_xray_ticket_obse_a825bd.py'
    example: |-
      result, error = sessionhistory.create_xray_ticket_observability(...)
      if error:
          # handle_error(error)
    tags:
      - 'create'
      - 'observability'
      - 'ray'
      - 'ticket'
      - 'x'
      - 'xray'
  # endregion functions