structs:
  # region models

  'BaseErrorResponse@gametelemetry':
    id: 'BaseErrorResponse@gametelemetry'
    name: 'BaseErrorResponse'
    fields:
      'error_code':
        type: 'int'
        required: true
      'error_message':
        type: 'str'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/base_error_response.py'
    example: |-
      base_error_response = gametelemetry_models.BaseErrorResponse.create(...)

  'GetNamespaceEventResponse@gametelemetry':
    id: 'GetNamespaceEventResponse@gametelemetry'
    name: 'GetNamespaceEventResponse'
    fields:
      'event_id':
        type: 'str'
        required: true
      'event_name':
        type: 'str'
        required: true
      'event_namespace':
        type: 'str'
        required: true
      'event_timestamp':
        type: 'str'
        required: true
      'flight_id':
        type: 'str'
        required: false
      'payload':
        type: 'Dict[str, Any]'
        required: false
      'user_id':
        type: 'str'
        required: false
      'user_namespace':
        type: 'str'
        required: false
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/get_namespace_event_response.py'
    example: |-
      get_namespace_event_response = gametelemetry_models.GetNamespaceEventResponse.create(...)

  'HTTPValidationError@gametelemetry':
    id: 'HTTPValidationError@gametelemetry'
    name: 'HTTPValidationError'
    fields:
      'detail':
        type: 'List[ValidationError]'
        required: false
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/http_validation_error.py'
    example: |-
      http_validation_error = gametelemetry_models.HTTPValidationError.create(...)

  'ListBaseResponseStr@gametelemetry':
    id: 'ListBaseResponseStr@gametelemetry'
    name: 'ListBaseResponseStr'
    fields:
      'data':
        type: 'List[str]'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/list_base_response_str.py'
    example: |-
      list_base_response_str = gametelemetry_models.ListBaseResponseStr.create(...)

  'PagedResponseGetNamespaceEventResponse@gametelemetry':
    id: 'PagedResponseGetNamespaceEventResponse@gametelemetry'
    name: 'PagedResponseGetNamespaceEventResponse'
    fields:
      'data':
        type: 'List[GetNamespaceEventResponse]'
        required: true
      'paging':
        type: 'Paging'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/paged_response_get_namespace_event_response.py'
    example: |-
      paged_response_get_namespace_event_response = gametelemetry_models.PagedResponseGetNamespaceEventResponse.create(...)

  'Paging@gametelemetry':
    id: 'Paging@gametelemetry'
    name: 'Paging'
    fields:
      'next_':
        type: 'str'
        required: false
      'previous':
        type: 'str'
        required: false
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/paging.py'
    example: |-
      paging = gametelemetry_models.Paging.create(...)

  'PlayTimeResponse@gametelemetry':
    id: 'PlayTimeResponse@gametelemetry'
    name: 'PlayTimeResponse'
    fields:
      'total_playtime':
        type: 'float'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/play_time_response.py'
    example: |-
      play_time_response = gametelemetry_models.PlayTimeResponse.create(...)

  'TelemetryBody@gametelemetry':
    id: 'TelemetryBody@gametelemetry'
    name: 'TelemetryBody'
    fields:
      'event_name':
        type: 'str'
        required: true
      'event_namespace':
        type: 'str'
        required: true
      'payload':
        type: 'Dict[str, Any]'
        required: true
      'client_timestamp':
        type: 'str'
        required: false
      'device_type':
        type: 'str'
        required: false
      'event_id':
        type: 'str'
        required: false
        description: |-
          Adding this `EventID` field in the request body does not override the `EventID` generated by server which is saved in the data lake
      'event_timestamp':
        type: 'str'
        required: false
        description: |-
          Adding this `EventTimestamp` field in the request body does not override the `EventTimestamp` generated by server which is saved in the data lake. To add specific timestamp of your telemetry data, please add it to ClientTimestamp field OR a new subfield in the `payload` field
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/telemetry_body.py'
    example: |-
      telemetry_body = gametelemetry_models.TelemetryBody.create(...)

  'ValidationError@gametelemetry':
    id: 'ValidationError@gametelemetry'
    name: 'ValidationError'
    fields:
      'loc':
        type: 'List[str]'
        required: true
      'msg':
        type: 'str'
        required: true
      'type_':
        type: 'str'
        required: true
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/models/validation_error.py'
    example: |-
      validation_error = gametelemetry_models.ValidationError.create(...)

  # endregion models

functions:

  'get_events_game_telemetry_v1_admin_namespaces_namespace_events_get@gametelemetry':
    id: 'get_events_game_telemetry_v1_admin_namespaces_namespace_events_get@gametelemetry'
    name: 'get_events_game_telemetry_v1_admin_namespaces_namespace_events_get'
    description: |-
      This endpoint requires valid JWT token and telemetry permission
      This endpoint retrieves event list
    parameters:
      'device_type':
        type: 'Optional[str]'
        required: false
        description: |-
          Game telemetry DeviceType.
      'end_time':
        type: 'Optional[str]'
        required: false
        description: |-
          End time of data to be queried. Default: Current time in UTC.
      'event_id':
        type: 'Optional[str]'
        required: false
        description: |-
          Game telemetry EventId.
      'event_name':
        type: 'Optional[str]'
        required: false
        description: |-
          Game telemetry EventName.
      'event_payload':
        type: 'Optional[str]'
        required: false
        description: |-
          Game telemetry payload to be query. Format: [foo].[bar]:[keyword]. e.g: player.username:tom*
      'flight_id':
        type: 'Optional[str]'
        required: false
        description: |-
          Game telemetry FlightId.
      'limit':
        type: 'Optional[int]'
        required: false
        description: |-
          Limit of response data number.
      'namespace':
        type: 'str'
        required: true
      'offset':
        type: 'Optional[int]'
        required: false
        description: |-
          Offset of response data number.
      'start_time':
        type: 'Optional[str]'
        required: false
        description: |-
          Start time of data to be queried. Default: Current time in UTC minus 1 day.
      'user_id':
        type: 'Optional[str]'
        required: false
        description: |-
          Game telemetry UserId.
    return_type: 'Tuple[Union[None, PagedResponseGetNamespaceEventResponse], Union[None, BaseErrorResponse, HTTPValidationError, HttpResponse]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.gametelemetry as gametelemetry'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/operations/telemetry/get_events_game_telemet_b2983d.py'
    example: |-
      result, error = gametelemetry.get_events_game_telemetry_v1_admin_namespaces_namespace_events_get(...)
      if error:
          # handle_error(error)
    tags:
      - 'admin'
      - 'events'
      - 'game'
      - 'get'
      - 'namespace'
      - 'namespaces'
      - 'telemetry'
      - 'v1'

  'get_namespaces_game_telemetry_v1_admin_namespaces_get@gametelemetry':
    id: 'get_namespaces_game_telemetry_v1_admin_namespaces_get@gametelemetry'
    name: 'get_namespaces_game_telemetry_v1_admin_namespaces_get'
    description: |-
      This endpoint requires valid JWT token and telemetry permission
      This endpoint retrieves namespace list
    parameters:
    return_type: 'Tuple[Union[None, ListBaseResponseStr], Union[None, BaseErrorResponse, HttpResponse]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.gametelemetry as gametelemetry'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/operations/telemetry/get_namespaces_game_tel_1106fd.py'
    example: |-
      result, error = gametelemetry.get_namespaces_game_telemetry_v1_admin_namespaces_get(...)
      if error:
          # handle_error(error)
    tags:
      - 'admin'
      - 'game'
      - 'get'
      - 'namespaces'
      - 'telemetry'
      - 'v1'

  'protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get@gametelemetry':
    id: 'protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get@gametelemetry'
    name: 'protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint retrieves player's total playtime in Steam for a specific game (AppId) and store them in service's cache.

      Players' Steam account must be set into public to enable the service fetch their total playtime data.
    parameters:
      'cookie':
        type: 'Optional[Union[str, HeaderStr]]'
        required: false
      'steam_id':
        type: 'str'
        required: true
    return_type: 'Tuple[Union[None, PlayTimeResponse], Union[None, BaseErrorResponse, HttpResponse]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.gametelemetry as gametelemetry'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/operations/gametelemetry_operations/protected_get_playtime__9a0e17.py'
    example: |-
      result, error = gametelemetry.protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get(...)
      if error:
          # handle_error(error)
    tags:
      - 'game'
      - 'gametelemetry'
      - 'get'
      - 'id'
      - 'ids'
      - 'operations'
      - 'playtime'
      - 'protected'
      - 'steam'
      - 'telemetry'
      - 'v1'

  'protected_save_events_game_telemetry_v1_protected_events_post@gametelemetry':
    id: 'protected_save_events_game_telemetry_v1_protected_events_post@gametelemetry'
    name: 'protected_save_events_game_telemetry_v1_protected_events_post'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint send events into designated streaming pipeline and each request can contain single or multiple events.


      Format of the event:

      - **EventNamespace (required)**: Namespace of the relevant game with domain name format.


      Only accept input with valid characters. Allowed characters: Aa-Zz0-9_.-




      It is encouraged to use alphanumeric only characters. _.- will be deprecated soon




      Example: accelbyte



      - **EventName (required)**: Name of the event.


      Only accept input with valid characters. Allowed characters: Aa-Zz0-9_.-




      It is encouraged to use alphanumeric only characters. _.- will be deprecated soon




      Example: player_killed, mission_accomplished



      - **Payload (required)**: An arbitrary json with the payload of the said event.


      Default maximum payload size is 1MB



      - **ClientTimestamp (optional)**: Timestamp of the event captured by the client SDK.

      - **DeviceType (optional)**: The device type of the user.
    parameters:
      'body':
        type: 'List[TelemetryBody]'
        required: true
      'cookie':
        type: 'Optional[Union[str, HeaderStr]]'
        required: false
    return_type: 'Tuple[None, Union[None, BaseErrorResponse, HttpResponse]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.gametelemetry as gametelemetry'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/operations/gametelemetry_operations/protected_save_events_g_832bbb.py'
    example: |-
      result, error = gametelemetry.protected_save_events_game_telemetry_v1_protected_events_post(...)
      if error:
          # handle_error(error)
    tags:
      - 'events'
      - 'game'
      - 'gametelemetry'
      - 'operations'
      - 'post'
      - 'protected'
      - 'save'
      - 'telemetry'
      - 'v1'

  'protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put@gametelemetry':
    id: 'protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put@gametelemetry'
    name: 'protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint update player's total playtime in a specific game (AppId) from service's cache.
    parameters:
      'cookie':
        type: 'Optional[Union[str, HeaderStr]]'
        required: false
      'playtime':
        type: 'str'
        required: true
      'steam_id':
        type: 'str'
        required: true
    return_type: 'Tuple[Union[None, PlayTimeResponse], Union[None, BaseErrorResponse, HttpResponse]]'
    imports:
      - 'from typing import Any, Dict, List, Optional, Tuple, Union'
      - 'from accelbyte_py_sdk.core import HttpResponse'
      - 'import accelbyte_py_sdk.api.gametelemetry as gametelemetry'
      - 'import accelbyte_py_sdk.api.gametelemetry.models as gametelemetry_models'
    files:
      - 'https://github.com/AccelByte/accelbyte-python-sdk/blob/main/accelbyte_py_sdk/api/gametelemetry/operations/gametelemetry_operations/protected_update_playti_4b5b85.py'
    example: |-
      result, error = gametelemetry.protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put(...)
      if error:
          # handle_error(error)
    tags:
      - 'game'
      - 'gametelemetry'
      - 'id'
      - 'ids'
      - 'operations'
      - 'playtime'
      - 'protected'
      - 'put'
      - 'steam'
      - 'telemetry'
      - 'update'
      - 'v1'
