symbols:
  # region models

  'ApimodelsXRayBulkTicketObservabilityRequest@cs.sessionhistory.mod':
    id: 'ApimodelsXRayBulkTicketObservabilityRequest@cs.sessionhistory.mod'
    name: 'ApimodelsXRayBulkTicketObservabilityRequest'
    type: 'model'
    fields:
      'TicketObservabilities':
        type: 'List<ApimodelsXRayTicketObservabilityRequest>'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ApimodelsXRayBulkTicketObservabilityRequest.cs'

  'ApimodelsXRayBulkTicketObservabilityResponse@cs.sessionhistory.mod':
    id: 'ApimodelsXRayBulkTicketObservabilityResponse@cs.sessionhistory.mod'
    name: 'ApimodelsXRayBulkTicketObservabilityResponse'
    type: 'model'
    fields:
      'TicketIDs':
        type: 'List<string>'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ApimodelsXRayBulkTicketObservabilityResponse.cs'

  'ApimodelsXRayTicketObservabilityRequest@cs.sessionhistory.mod':
    id: 'ApimodelsXRayTicketObservabilityRequest@cs.sessionhistory.mod'
    name: 'ApimodelsXRayTicketObservabilityRequest'
    type: 'model'
    fields:
      'Action':
        type: 'string'
        required: true
      'GameMode':
        type: 'string'
        required: true
      'IsBackfillMatch':
        type: 'bool'
        required: true
      'IsRuleSetFlexed':
        type: 'bool'
        required: true
      'Namespace':
        type: 'string'
        required: true
      'SessionTickID':
        type: 'string'
        required: true
      'TickID':
        type: 'long'
        required: true
      'TicketID':
        type: 'string'
        required: true
      'Timestamp':
        type: 'DateTime'
        required: true
      'ActiveAllianceRule':
        type: 'ModelsAllianceRule'
        required: false
      'ActiveMatchingRule':
        type: 'List<ModelsMatchingRule>'
        required: false
      'Function':
        type: 'string'
        required: false
      'Iteration':
        type: 'int'
        required: false
      'MatchID':
        type: 'string'
        required: false
      'RemainingPlayersPerTicket':
        type: 'List<int>'
        required: false
      'RemainingTickets':
        type: 'int'
        required: false
      'TimeToMatchSec':
        type: 'double'
        required: false
      'UnbackfillReason':
        type: 'string'
        required: false
      'UnmatchReason':
        type: 'string'
        required: false
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ApimodelsXRayTicketObservabilityRequest.cs'

  'ApimodelsXRayTicketObservabilityResponse@cs.sessionhistory.mod':
    id: 'ApimodelsXRayTicketObservabilityResponse@cs.sessionhistory.mod'
    name: 'ApimodelsXRayTicketObservabilityResponse'
    type: 'model'
    fields:
      'TicketID':
        type: 'string'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ApimodelsXRayTicketObservabilityResponse.cs'

  'ModelsAllianceRule@cs.sessionhistory.mod':
    id: 'ModelsAllianceRule@cs.sessionhistory.mod'
    name: 'ModelsAllianceRule'
    type: 'model'
    fields:
      'MaxNumber':
        type: 'int'
        required: true
      'MinNumber':
        type: 'int'
        required: true
      'PlayerMaxNumber':
        type: 'int'
        required: true
      'PlayerMinNumber':
        type: 'int'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ModelsAllianceRule.cs'

  'ModelsMatchingRule@cs.sessionhistory.mod':
    id: 'ModelsMatchingRule@cs.sessionhistory.mod'
    name: 'ModelsMatchingRule'
    type: 'model'
    fields:
      'Attribute':
        type: 'string'
        required: true
      'Criteria':
        type: 'string'
        required: true
      'Reference':
        type: 'double'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ModelsMatchingRule.cs'

  'ResponseError@cs.sessionhistory.mod':
    id: 'ResponseError@cs.sessionhistory.mod'
    name: 'ResponseError'
    type: 'model'
    fields:
      'Attributes':
        type: 'Dictionary<string, string>'
        required: true
      'ErrorCode':
        type: 'int'
        required: true
      'ErrorMessage':
        type: 'string'
        required: true
      'Message':
        type: 'string'
        required: true
      'Name':
        type: 'string'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Model/ResponseError.cs'

  # endregion models

  # region functions

  'CreateXrayBulkTicketObservability@cs.sessionhistory.fun':
    id: 'CreateXrayBulkTicketObservability@cs.sessionhistory.fun'
    name: 'CreateXrayBulkTicketObservability'
    type: 'function'
    description: |-
      Create bulk ticket observability request
      Request body details (all attributes are optional):
      Timestamp : timestamp when calling this endpoint
      Action : support one of the following value:
      1. "matchFound"
      2. "matchNotFound"
      3. "flexed"
      PartyID : ticket Party ID
      MatchID : match ID will be filled only when match found
      Namespace : ticket current namespace
      GameMode : ticket current matchpool
      ActiveAllianceRule : current active alliance ruleset
      ActiveMatchingRule : current active matching ruleset
      Function : name of the function that called the endpoint
      Iteration : total iteration before match found
      TimeToMatchSec : time to match (in seconds) will be filled only when match found
      UnmatchReason : reason when unable to find match
      RemainingTickets : remaining ticket when unable to find match
      RemainingPlayersPerTicket : remaining players when unable to find match
      UnbackfillReason : reason when unable to backfill
      IsBackfillMatch : flag to distinguish between new match and backfill match
      IsRuleSetFlexed : flag if ruleset is getting flexed
      TickID : tick id for the matchmaking tick
      SessionTickID : session tick id for differentiate session when doing matches
    arguments:
      'Body':
        type: 'ApimodelsXRayBulkTicketObservabilityRequest'
        required: true
      'Namespace':
        type: 'string'
        required: true
        description: |-
          namespace of the game
    return_type: 'ApimodelsXRayBulkTicketObservabilityResponse'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Operation;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Wrapper/XRay.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Operation/XRay/CreateXrayBulkTicketObservability.cs'
    example: |-
      try
      {
          var operation = sdk.Sessionhistory.XRay.CreateXrayBulkTicketObservabilityOp
              .Build();

          var response = sdk.Sessionhistory.XRay.CreateXrayBulkTicketObservability(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'bulk'
      - 'create'
      - 'observability'
      - 'ray'
      - 'ticket'
      - 'x'
      - 'xray'

  'CreateXrayTicketObservability@cs.sessionhistory.fun':
    id: 'CreateXrayTicketObservability@cs.sessionhistory.fun'
    name: 'CreateXrayTicketObservability'
    type: 'function'
    description: |-
      Create ticket observability request
      Request body details (all attributes are optional):
      Timestamp : timestamp when calling this endpoint
      Action : support one of the following value:
      1. "matchFound"
      2. "matchNotFound"
      3. "flexed"
      TicketID : ticket ID
      MatchID : match ID will be filled only when match found
      Namespace : ticket current namespace
      GameMode : ticket current matchpool
      ActiveAllianceRule : current active alliance ruleset
      ActiveMatchingRule : current active matching ruleset
      Function : name of the function that called the endpoint
      Iteration : total iteration before match found
      TimeToMatchSec : time to match (in seconds) will be filled only when match found
      UnmatchReason : reason when unable to find match
      RemainingTickets : remaining ticket when unable to find match
      RemainingPlayersPerTicket : remaining players when unable to find match
      UnbackfillReason : reason when unable to backfill
      IsBackfillMatch : flag to distinguish between new match and backfill match
      IsRuleSetFlexed : flag if ruleset is getting flexed
      TickID : tick id for the matchmaking tick
      SessionTickID : session tick id for differentiate session when doing matches
    arguments:
      'Body':
        type: 'ApimodelsXRayTicketObservabilityRequest'
        required: true
      'Namespace':
        type: 'string'
        required: true
        description: |-
          namespace of the game
    return_type: 'ApimodelsXRayTicketObservabilityResponse'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Model;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Operation;'
      - 'using AccelByte.Sdk.Api.Sessionhistory.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Wrapper/XRay.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Sessionhistory/Operation/XRay/CreateXrayTicketObservability.cs'
    example: |-
      try
      {
          var operation = sdk.Sessionhistory.XRay.CreateXrayTicketObservabilityOp
              .Build();

          var response = sdk.Sessionhistory.XRay.CreateXrayTicketObservability(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'create'
      - 'observability'
      - 'ray'
      - 'ticket'
      - 'x'
      - 'xray'
  # endregion functions