symbols:
  # region models

  'BaseErrorResponse@cs.gametelemetry.mod':
    id: 'BaseErrorResponse@cs.gametelemetry.mod'
    name: 'BaseErrorResponse'
    type: 'model'
    fields:
      'ErrorCode':
        type: 'long'
        required: true
      'ErrorMessage':
        type: 'string'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/BaseErrorResponse.cs'

  'GetNamespaceEventResponse@cs.gametelemetry.mod':
    id: 'GetNamespaceEventResponse@cs.gametelemetry.mod'
    name: 'GetNamespaceEventResponse'
    type: 'model'
    fields:
      'EventId':
        type: 'string'
        required: true
      'EventName':
        type: 'string'
        required: true
      'EventNamespace':
        type: 'string'
        required: true
      'EventTimestamp':
        type: 'string'
        required: true
      'FlightId':
        type: 'string'
        required: false
      'Payload':
        type: 'Dictionary<string, object>'
        required: false
      'UserId':
        type: 'string'
        required: false
      'UserNamespace':
        type: 'string'
        required: false
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/GetNamespaceEventResponse.cs'

  'HTTPValidationError@cs.gametelemetry.mod':
    id: 'HTTPValidationError@cs.gametelemetry.mod'
    name: 'HTTPValidationError'
    type: 'model'
    fields:
      'Detail':
        type: 'List<ValidationError>'
        required: false
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/HTTPValidationError.cs'

  'ListBaseResponseStr@cs.gametelemetry.mod':
    id: 'ListBaseResponseStr@cs.gametelemetry.mod'
    name: 'ListBaseResponseStr'
    type: 'model'
    fields:
      'Data':
        type: 'List<string>'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/ListBaseResponseStr.cs'

  'PagedResponseGetNamespaceEventResponse@cs.gametelemetry.mod':
    id: 'PagedResponseGetNamespaceEventResponse@cs.gametelemetry.mod'
    name: 'PagedResponseGetNamespaceEventResponse'
    type: 'model'
    fields:
      'Data':
        type: 'List<GetNamespaceEventResponse>'
        required: true
      'Paging':
        type: 'Paging'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/PagedResponseGetNamespaceEventResponse.cs'

  'Paging@cs.gametelemetry.mod':
    id: 'Paging@cs.gametelemetry.mod'
    name: 'Paging'
    type: 'model'
    fields:
      'Next':
        type: 'string'
        required: false
      'Previous':
        type: 'string'
        required: false
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/Paging.cs'

  'PlayTimeResponse@cs.gametelemetry.mod':
    id: 'PlayTimeResponse@cs.gametelemetry.mod'
    name: 'PlayTimeResponse'
    type: 'model'
    fields:
      'TotalPlaytime':
        type: 'double'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/PlayTimeResponse.cs'

  'TelemetryBody@cs.gametelemetry.mod':
    id: 'TelemetryBody@cs.gametelemetry.mod'
    name: 'TelemetryBody'
    type: 'model'
    fields:
      'EventName':
        type: 'string'
        required: true
      'EventNamespace':
        type: 'string'
        required: true
      'Payload':
        type: 'Dictionary<string, object>'
        required: true
      'ClientTimestamp':
        type: 'DateTime'
        required: false
      'DeviceType':
        type: 'string'
        required: false
      'EventId':
        type: 'string'
        required: false
        description: |-
          Adding this `EventID` field in the request body does not override the `EventID` generated by server which is saved in the data lake
      'EventTimestamp':
        type: 'DateTime'
        required: false
        description: |-
          Adding this `EventTimestamp` field in the request body does not override the `EventTimestamp` generated by server which is saved in the data lake. To add specific timestamp of your telemetry data, please add it to ClientTimestamp field OR a new subfield in the `payload` field
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/TelemetryBody.cs'

  'ValidationError@cs.gametelemetry.mod':
    id: 'ValidationError@cs.gametelemetry.mod'
    name: 'ValidationError'
    type: 'model'
    fields:
      'Loc':
        type: 'List<string>'
        required: true
      'Msg':
        type: 'string'
        required: true
      'Type':
        type: 'string'
        required: true
    imports:
      - 'using System;'
      - 'using System.Collections.Generic;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Model/ValidationError.cs'

  # endregion models

  # region functions

  'GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet@cs.gametelemetry.fun':
    id: 'GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet@cs.gametelemetry.fun'
    name: 'GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token and telemetry permission
      This endpoint retrieves event list
    arguments:
      'DeviceType':
        type: 'string'
        required: false
        description: |-
          Game telemetry DeviceType.
      'EndTime':
        type: 'string'
        required: false
        description: |-
          End time of data to be queried. Default: Current time in UTC.
      'EventId':
        type: 'string'
        required: false
        description: |-
          Game telemetry EventId.
      'EventName':
        type: 'string'
        required: false
        description: |-
          Game telemetry EventName.
      'EventPayload':
        type: 'string'
        required: false
        description: |-
          Game telemetry payload to be query. Format: [foo].[bar]:[keyword]. e.g: player.username:tom*
      'FlightId':
        type: 'string'
        required: false
        description: |-
          Game telemetry FlightId.
      'Limit':
        type: 'long'
        required: false
        description: |-
          Limit of response data number.
      'Namespace':
        type: 'string'
        required: true
      'Offset':
        type: 'long'
        required: false
        description: |-
          Offset of response data number.
      'StartTime':
        type: 'string'
        required: false
        description: |-
          Start time of data to be queried. Default: Current time in UTC minus 1 day.
      'UserId':
        type: 'string'
        required: false
        description: |-
          Game telemetry UserId.
    return_type: 'PagedResponseGetNamespaceEventResponse'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Operation;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Wrapper/Telemetry.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Operation/Telemetry/GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet.cs'
    example: |-
      try
      {
          var operation = sdk.Gametelemetry.Telemetry.GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGetOp
              .SetDeviceType(...)
              .SetEndTime(...)
              .SetEventId(...)
              .SetEventName(...)
              .SetEventPayload(...)
              .SetFlightId(...)
              .SetLimit(...)
              .SetOffset(...)
              .SetStartTime(...)
              .SetUserId(...)
              .Build(
                  namespace_,
              );

          var response = sdk.Gametelemetry.Telemetry.GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'admin'
      - 'events'
      - 'game'
      - 'get'
      - 'namespace'
      - 'namespaces'
      - 'telemetry'
      - 'v1'

  'GetNamespacesGameTelemetryV1AdminNamespacesGet@cs.gametelemetry.fun':
    id: 'GetNamespacesGameTelemetryV1AdminNamespacesGet@cs.gametelemetry.fun'
    name: 'GetNamespacesGameTelemetryV1AdminNamespacesGet'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token and telemetry permission
      This endpoint retrieves namespace list
    return_type: 'ListBaseResponseStr'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Operation;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Wrapper/Telemetry.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Operation/Telemetry/GetNamespacesGameTelemetryV1AdminNamespacesGet.cs'
    example: |-
      try
      {
          var operation = sdk.Gametelemetry.Telemetry.GetNamespacesGameTelemetryV1AdminNamespacesGetOp
              .Build();

          var response = sdk.Gametelemetry.Telemetry.GetNamespacesGameTelemetryV1AdminNamespacesGet(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'admin'
      - 'game'
      - 'get'
      - 'namespaces'
      - 'telemetry'
      - 'v1'

  'ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet@cs.gametelemetry.fun':
    id: 'ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet@cs.gametelemetry.fun'
    name: 'ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint retrieves player's total playtime in Steam for a specific game (AppId) and store them in service's cache.

      Players' Steam account must be set into public to enable the service fetch their total playtime data.
    arguments:
      'Cookie':
        type: 'string'
        required: false
      'SteamId':
        type: 'string'
        required: true
    return_type: 'PlayTimeResponse'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Operation;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Wrapper/GametelemetryOperations.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Operation/GametelemetryOperations/ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet.cs'
    example: |-
      try
      {
          var operation = sdk.Gametelemetry.GametelemetryOperations.ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGetOp
              .SetCookie(...)
              .Build(
                  steamId,
              );

          var response = sdk.Gametelemetry.GametelemetryOperations.ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'game'
      - 'gametelemetry'
      - 'get'
      - 'id'
      - 'ids'
      - 'operations'
      - 'playtime'
      - 'protected'
      - 'steam'
      - 'telemetry'
      - 'v1'

  'ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost@cs.gametelemetry.fun':
    id: 'ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost@cs.gametelemetry.fun'
    name: 'ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint send events into designated streaming pipeline and each request can contain single or multiple events.


      Format of the event:

      - **EventNamespace (required)**: Namespace of the relevant game with domain name format.


      Only accept input with valid characters. Allowed characters: Aa-Zz0-9_.-




      It is encouraged to use alphanumeric only characters. _.- will be deprecated soon




      Example: accelbyte



      - **EventName (required)**: Name of the event.


      Only accept input with valid characters. Allowed characters: Aa-Zz0-9_.-




      It is encouraged to use alphanumeric only characters. _.- will be deprecated soon




      Example: player_killed, mission_accomplished



      - **Payload (required)**: An arbitrary json with the payload of the said event.


      Default maximum payload size is 1MB



      - **ClientTimestamp (optional)**: Timestamp of the event captured by the client SDK.

      - **DeviceType (optional)**: The device type of the user.
    arguments:
      'Body':
        type: 'List<TelemetryBody>'
        required: true
      'Cookie':
        type: 'string'
        required: false
    return_type: 'void'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Operation;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Wrapper/GametelemetryOperations.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Operation/GametelemetryOperations/ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost.cs'
    example: |-
      try
      {
          var operation = sdk.Gametelemetry.GametelemetryOperations.ProtectedSaveEventsGameTelemetryV1ProtectedEventsPostOp
              .SetCookie(...)
              .Build(
                  body,
              );

          sdk.Gametelemetry.GametelemetryOperations.ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'events'
      - 'game'
      - 'gametelemetry'
      - 'operations'
      - 'post'
      - 'protected'
      - 'save'
      - 'telemetry'
      - 'v1'

  'ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut@cs.gametelemetry.fun':
    id: 'ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut@cs.gametelemetry.fun'
    name: 'ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint update player's total playtime in a specific game (AppId) from service's cache.
    arguments:
      'Cookie':
        type: 'string'
        required: false
      'Playtime':
        type: 'string'
        required: true
      'SteamId':
        type: 'string'
        required: true
    return_type: 'PlayTimeResponse'
    imports:
      - 'using AccelByte.Sdk.Core;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Model;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Operation;'
      - 'using AccelByte.Sdk.Api.Gametelemetry.Wrapper;'
    files:
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Wrapper/GametelemetryOperations.cs'
      - 'https://github.com/AccelByte/accelbyte-csharp-sdk/blob/main/AccelByte.Sdk/Api/Gametelemetry/Operation/GametelemetryOperations/ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut.cs'
    example: |-
      try
      {
          var operation = sdk.Gametelemetry.GametelemetryOperations.ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePutOp
              .SetCookie(...)
              .Build(
                  playtime,
                  steamId,
              );

          var response = sdk.Gametelemetry.GametelemetryOperations.ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'game'
      - 'gametelemetry'
      - 'id'
      - 'ids'
      - 'operations'
      - 'playtime'
      - 'protected'
      - 'put'
      - 'steam'
      - 'telemetry'
      - 'update'
      - 'v1'
  # endregion functions