symbols:
  # region models

  'ApimodelsXRayBulkTicketObservabilityRequest@jv.sessionhistory.mod':
    id: 'ApimodelsXRayBulkTicketObservabilityRequest@jv.sessionhistory.mod'
    name: 'ApimodelsXRayBulkTicketObservabilityRequest'
    type: 'model'
    fields:
      'ticketObservabilities':
        type: 'List<ApimodelsXRayTicketObservabilityRequest>'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ApimodelsXRayBulkTicketObservabilityRequest.java'

  'ApimodelsXRayBulkTicketObservabilityResponse@jv.sessionhistory.mod':
    id: 'ApimodelsXRayBulkTicketObservabilityResponse@jv.sessionhistory.mod'
    name: 'ApimodelsXRayBulkTicketObservabilityResponse'
    type: 'model'
    fields:
      'ticketIDs':
        type: 'List<String>'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ApimodelsXRayBulkTicketObservabilityResponse.java'

  'ApimodelsXRayTicketObservabilityRequest@jv.sessionhistory.mod':
    id: 'ApimodelsXRayTicketObservabilityRequest@jv.sessionhistory.mod'
    name: 'ApimodelsXRayTicketObservabilityRequest'
    type: 'model'
    fields:
      'action':
        type: 'String'
        required: true
      'gameMode':
        type: 'String'
        required: true
      'isBackfillMatch':
        type: 'Boolean'
        required: true
      'isRuleSetFlexed':
        type: 'Boolean'
        required: true
      'namespace':
        type: 'String'
        required: true
      'sessionTickID':
        type: 'String'
        required: true
      'tickID':
        type: 'Long'
        required: true
      'ticketID':
        type: 'String'
        required: true
      'timestamp':
        type: 'String'
        required: true
      'activeAllianceRule':
        type: 'ModelsAllianceRule'
        required: false
      'activeMatchingRule':
        type: 'List<ModelsMatchingRule>'
        required: false
      'function':
        type: 'String'
        required: false
      'iteration':
        type: 'Integer'
        required: false
      'matchID':
        type: 'String'
        required: false
      'remainingPlayersPerTicket':
        type: 'List<Integer>'
        required: false
      'remainingTickets':
        type: 'Integer'
        required: false
      'timeToMatchSec':
        type: 'Float'
        required: false
      'unbackfillReason':
        type: 'String'
        required: false
      'unmatchReason':
        type: 'String'
        required: false
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ApimodelsXRayTicketObservabilityRequest.java'

  'ApimodelsXRayTicketObservabilityResponse@jv.sessionhistory.mod':
    id: 'ApimodelsXRayTicketObservabilityResponse@jv.sessionhistory.mod'
    name: 'ApimodelsXRayTicketObservabilityResponse'
    type: 'model'
    fields:
      'ticketID':
        type: 'String'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ApimodelsXRayTicketObservabilityResponse.java'

  'ModelsAllianceRule@jv.sessionhistory.mod':
    id: 'ModelsAllianceRule@jv.sessionhistory.mod'
    name: 'ModelsAllianceRule'
    type: 'model'
    fields:
      'maxNumber':
        type: 'Integer'
        required: true
      'minNumber':
        type: 'Integer'
        required: true
      'playerMaxNumber':
        type: 'Integer'
        required: true
      'playerMinNumber':
        type: 'Integer'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ModelsAllianceRule.java'

  'ModelsMatchingRule@jv.sessionhistory.mod':
    id: 'ModelsMatchingRule@jv.sessionhistory.mod'
    name: 'ModelsMatchingRule'
    type: 'model'
    fields:
      'attribute':
        type: 'String'
        required: true
      'criteria':
        type: 'String'
        required: true
      'reference':
        type: 'Float'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ModelsMatchingRule.java'

  'ResponseError@jv.sessionhistory.mod':
    id: 'ResponseError@jv.sessionhistory.mod'
    name: 'ResponseError'
    type: 'model'
    fields:
      'attributes':
        type: 'Map<String, String>'
        required: true
      'errorCode':
        type: 'Integer'
        required: true
      'errorMessage':
        type: 'String'
        required: true
      'message':
        type: 'String'
        required: true
      'name':
        type: 'String'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/models/ResponseError.java'

  # endregion models

  # region functions

  'CreateXrayBulkTicketObservability@jv.sessionhistory.fun':
    id: 'CreateXrayBulkTicketObservability@jv.sessionhistory.fun'
    name: 'CreateXrayBulkTicketObservability'
    type: 'function'
    description: |-
      Create bulk ticket observability request
      Request body details (all attributes are optional):
      Timestamp : timestamp when calling this endpoint
      Action : support one of the following value:
      1. "matchFound"
      2. "matchNotFound"
      3. "flexed"
      PartyID : ticket Party ID
      MatchID : match ID will be filled only when match found
      Namespace : ticket current namespace
      GameMode : ticket current matchpool
      ActiveAllianceRule : current active alliance ruleset
      ActiveMatchingRule : current active matching ruleset
      Function : name of the function that called the endpoint
      Iteration : total iteration before match found
      TimeToMatchSec : time to match (in seconds) will be filled only when match found
      UnmatchReason : reason when unable to find match
      RemainingTickets : remaining ticket when unable to find match
      RemainingPlayersPerTicket : remaining players when unable to find match
      UnbackfillReason : reason when unable to backfill
      IsBackfillMatch : flag to distinguish between new match and backfill match
      IsRuleSetFlexed : flag if ruleset is getting flexed
      TickID : tick id for the matchmaking tick
      SessionTickID : session tick id for differentiate session when doing matches
    arguments:
      'body':
        type: 'ApimodelsXRayBulkTicketObservabilityRequest'
        required: true
      'namespace':
        type: 'String'
        required: true
        description: |-
          namespace of the game
    return_type: 'ApimodelsXRayBulkTicketObservabilityResponse'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.operations.x_ray.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/wrappers/XRay.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/operations/x_ray/CreateXrayBulkTicketObservability.java'
    example: |-
      try {
          final CreateXrayBulkTicketObservability operation = CreateXrayBulkTicketObservability.builder()
              .build(
                  body,
                  namespace,
              );

          final XRay wrapper = new XRay(sdk);
          final ApimodelsXRayBulkTicketObservabilityResponse response = wrapper.createXrayBulkTicketObservability(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'bulk'
      - 'create'
      - 'observability'
      - 'ray'
      - 'ticket'
      - 'x'
      - 'xray'

  'CreateXrayTicketObservability@jv.sessionhistory.fun':
    id: 'CreateXrayTicketObservability@jv.sessionhistory.fun'
    name: 'CreateXrayTicketObservability'
    type: 'function'
    description: |-
      Create ticket observability request
      Request body details (all attributes are optional):
      Timestamp : timestamp when calling this endpoint
      Action : support one of the following value:
      1. "matchFound"
      2. "matchNotFound"
      3. "flexed"
      TicketID : ticket ID
      MatchID : match ID will be filled only when match found
      Namespace : ticket current namespace
      GameMode : ticket current matchpool
      ActiveAllianceRule : current active alliance ruleset
      ActiveMatchingRule : current active matching ruleset
      Function : name of the function that called the endpoint
      Iteration : total iteration before match found
      TimeToMatchSec : time to match (in seconds) will be filled only when match found
      UnmatchReason : reason when unable to find match
      RemainingTickets : remaining ticket when unable to find match
      RemainingPlayersPerTicket : remaining players when unable to find match
      UnbackfillReason : reason when unable to backfill
      IsBackfillMatch : flag to distinguish between new match and backfill match
      IsRuleSetFlexed : flag if ruleset is getting flexed
      TickID : tick id for the matchmaking tick
      SessionTickID : session tick id for differentiate session when doing matches
    arguments:
      'body':
        type: 'ApimodelsXRayTicketObservabilityRequest'
        required: true
      'namespace':
        type: 'String'
        required: true
        description: |-
          namespace of the game
    return_type: 'ApimodelsXRayTicketObservabilityResponse'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.models.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.operations.x_ray.*;'
      - 'import net.accelbyte.sdk.api.sessionhistory.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/wrappers/XRay.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/sessionhistory/operations/x_ray/CreateXrayTicketObservability.java'
    example: |-
      try {
          final CreateXrayTicketObservability operation = CreateXrayTicketObservability.builder()
              .build(
                  body,
                  namespace,
              );

          final XRay wrapper = new XRay(sdk);
          final ApimodelsXRayTicketObservabilityResponse response = wrapper.createXrayTicketObservability(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'create'
      - 'observability'
      - 'ray'
      - 'ticket'
      - 'x'
      - 'xray'
  # endregion functions