symbols:
  # region models

  'BaseErrorResponse@jv.gametelemetry.mod':
    id: 'BaseErrorResponse@jv.gametelemetry.mod'
    name: 'BaseErrorResponse'
    type: 'model'
    fields:
      'errorCode':
        type: 'Integer'
        required: true
      'errorMessage':
        type: 'String'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/BaseErrorResponse.java'

  'GetNamespaceEventResponse@jv.gametelemetry.mod':
    id: 'GetNamespaceEventResponse@jv.gametelemetry.mod'
    name: 'GetNamespaceEventResponse'
    type: 'model'
    fields:
      'eventId':
        type: 'String'
        required: true
      'eventName':
        type: 'String'
        required: true
      'eventNamespace':
        type: 'String'
        required: true
      'eventTimestamp':
        type: 'String'
        required: true
      'flightId':
        type: 'String'
        required: false
      'payload':
        type: 'Map<String, ?>'
        required: false
      'userId':
        type: 'String'
        required: false
      'userNamespace':
        type: 'String'
        required: false
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/GetNamespaceEventResponse.java'

  'HTTPValidationError@jv.gametelemetry.mod':
    id: 'HTTPValidationError@jv.gametelemetry.mod'
    name: 'HTTPValidationError'
    type: 'model'
    fields:
      'detail':
        type: 'List<ValidationError>'
        required: false
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/HTTPValidationError.java'

  'ListBaseResponseStr@jv.gametelemetry.mod':
    id: 'ListBaseResponseStr@jv.gametelemetry.mod'
    name: 'ListBaseResponseStr'
    type: 'model'
    fields:
      'data':
        type: 'List<String>'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/ListBaseResponseStr.java'

  'PagedResponseGetNamespaceEventResponse@jv.gametelemetry.mod':
    id: 'PagedResponseGetNamespaceEventResponse@jv.gametelemetry.mod'
    name: 'PagedResponseGetNamespaceEventResponse'
    type: 'model'
    fields:
      'data':
        type: 'List<GetNamespaceEventResponse>'
        required: true
      'paging':
        type: 'Paging'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/PagedResponseGetNamespaceEventResponse.java'

  'Paging@jv.gametelemetry.mod':
    id: 'Paging@jv.gametelemetry.mod'
    name: 'Paging'
    type: 'model'
    fields:
      'next':
        type: 'String'
        required: false
      'previous':
        type: 'String'
        required: false
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/Paging.java'

  'PlayTimeResponse@jv.gametelemetry.mod':
    id: 'PlayTimeResponse@jv.gametelemetry.mod'
    name: 'PlayTimeResponse'
    type: 'model'
    fields:
      'totalPlaytime':
        type: 'Float'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/PlayTimeResponse.java'

  'TelemetryBody@jv.gametelemetry.mod':
    id: 'TelemetryBody@jv.gametelemetry.mod'
    name: 'TelemetryBody'
    type: 'model'
    fields:
      'eventName':
        type: 'String'
        required: true
      'eventNamespace':
        type: 'String'
        required: true
      'payload':
        type: 'Map<String, ?>'
        required: true
      'clientTimestamp':
        type: 'String'
        required: false
      'deviceType':
        type: 'String'
        required: false
      'eventId':
        type: 'String'
        required: false
        description: |-
          Adding this `EventID` field in the request body does not override the `EventID` generated by server which is saved in the data lake
      'eventTimestamp':
        type: 'String'
        required: false
        description: |-
          Adding this `EventTimestamp` field in the request body does not override the `EventTimestamp` generated by server which is saved in the data lake. To add specific timestamp of your telemetry data, please add it to ClientTimestamp field OR a new subfield in the `payload` field
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/TelemetryBody.java'

  'ValidationError@jv.gametelemetry.mod':
    id: 'ValidationError@jv.gametelemetry.mod'
    name: 'ValidationError'
    type: 'model'
    fields:
      'loc':
        type: 'List<String>'
        required: true
      'msg':
        type: 'String'
        required: true
      'type':
        type: 'String'
        required: true
    imports:
      - 'import java.util.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/models/ValidationError.java'

  # endregion models

  # region functions

  'GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet@jv.gametelemetry.fun':
    id: 'GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet@jv.gametelemetry.fun'
    name: 'GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token and telemetry permission
      This endpoint retrieves event list
    arguments:
      'deviceType':
        type: 'String'
        required: false
        description: |-
          Game telemetry DeviceType.
      'endTime':
        type: 'String'
        required: false
        description: |-
          End time of data to be queried. Default: Current time in UTC.
      'eventId':
        type: 'String'
        required: false
        description: |-
          Game telemetry EventId.
      'eventName':
        type: 'String'
        required: false
        description: |-
          Game telemetry EventName.
      'eventPayload':
        type: 'String'
        required: false
        description: |-
          Game telemetry payload to be query. Format: [foo].[bar]:[keyword]. e.g: player.username:tom*
      'flightId':
        type: 'String'
        required: false
        description: |-
          Game telemetry FlightId.
      'limit':
        type: 'Integer'
        required: false
        description: |-
          Limit of response data number.
      'namespace':
        type: 'String'
        required: true
      'offset':
        type: 'Integer'
        required: false
        description: |-
          Offset of response data number.
      'startTime':
        type: 'String'
        required: false
        description: |-
          Start time of data to be queried. Default: Current time in UTC minus 1 day.
      'userId':
        type: 'String'
        required: false
        description: |-
          Game telemetry UserId.
    return_type: 'PagedResponseGetNamespaceEventResponse'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.operations.telemetry.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/wrappers/Telemetry.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/operations/telemetry/GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet.java'
    example: |-
      try {
          final GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet operation = GetEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet.builder()
              .deviceType(...)
              .endTime(...)
              .eventId(...)
              .eventName(...)
              .eventPayload(...)
              .flightId(...)
              .limit(...)
              .offset(...)
              .startTime(...)
              .userId(...)
              .build(
                  namespace,
              );

          final Telemetry wrapper = new Telemetry(sdk);
          final PagedResponseGetNamespaceEventResponse response = wrapper.getEventsGameTelemetryV1AdminNamespacesNamespaceEventsGet(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'admin'
      - 'events'
      - 'game'
      - 'get'
      - 'namespace'
      - 'namespaces'
      - 'telemetry'
      - 'v1'

  'GetNamespacesGameTelemetryV1AdminNamespacesGet@jv.gametelemetry.fun':
    id: 'GetNamespacesGameTelemetryV1AdminNamespacesGet@jv.gametelemetry.fun'
    name: 'GetNamespacesGameTelemetryV1AdminNamespacesGet'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token and telemetry permission
      This endpoint retrieves namespace list
    return_type: 'ListBaseResponseStr'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.operations.telemetry.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/wrappers/Telemetry.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/operations/telemetry/GetNamespacesGameTelemetryV1AdminNamespacesGet.java'
    example: |-
      try {
          final GetNamespacesGameTelemetryV1AdminNamespacesGet operation = GetNamespacesGameTelemetryV1AdminNamespacesGet.builder()
              .build();

          final Telemetry wrapper = new Telemetry(sdk);
          final ListBaseResponseStr response = wrapper.getNamespacesGameTelemetryV1AdminNamespacesGet(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'admin'
      - 'game'
      - 'get'
      - 'namespaces'
      - 'telemetry'
      - 'v1'

  'ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet@jv.gametelemetry.fun':
    id: 'ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet@jv.gametelemetry.fun'
    name: 'ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint retrieves player's total playtime in Steam for a specific game (AppId) and store them in service's cache.

      Players' Steam account must be set into public to enable the service fetch their total playtime data.
    arguments:
      'cookie':
        type: 'String'
        required: false
      'steamId':
        type: 'String'
        required: true
    return_type: 'PlayTimeResponse'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.operations.gametelemetry_operations.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/wrappers/GametelemetryOperations.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/operations/gametelemetry_operations/ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet.java'
    example: |-
      try {
          final ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet operation = ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet.builder()
              .cookie(...)
              .build(
                  steamId,
              );

          final GametelemetryOperations wrapper = new GametelemetryOperations(sdk);
          final PlayTimeResponse response = wrapper.protectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'game'
      - 'gametelemetry'
      - 'get'
      - 'id'
      - 'ids'
      - 'operations'
      - 'playtime'
      - 'protected'
      - 'steam'
      - 'telemetry'
      - 'v1'

  'ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost@jv.gametelemetry.fun':
    id: 'ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost@jv.gametelemetry.fun'
    name: 'ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint send events into designated streaming pipeline and each request can contain single or multiple events.


      Format of the event:

      - **EventNamespace (required)**: Namespace of the relevant game with domain name format.


      Only accept input with valid characters. Allowed characters: Aa-Zz0-9_.-




      It is encouraged to use alphanumeric only characters. _.- will be deprecated soon




      Example: accelbyte



      - **EventName (required)**: Name of the event.


      Only accept input with valid characters. Allowed characters: Aa-Zz0-9_.-




      It is encouraged to use alphanumeric only characters. _.- will be deprecated soon




      Example: player_killed, mission_accomplished



      - **Payload (required)**: An arbitrary json with the payload of the said event.


      Default maximum payload size is 1MB



      - **ClientTimestamp (optional)**: Timestamp of the event captured by the client SDK.

      - **DeviceType (optional)**: The device type of the user.
    arguments:
      'body':
        type: 'List<TelemetryBody>'
        required: true
      'cookie':
        type: 'String'
        required: false
    return_type: 'void'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.operations.gametelemetry_operations.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/wrappers/GametelemetryOperations.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/operations/gametelemetry_operations/ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost.java'
    example: |-
      try {
          final ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost operation = ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost.builder()
              .cookie(...)
              .build(
                  body,
              );

          final GametelemetryOperations wrapper = new GametelemetryOperations(sdk);
          wrapper.protectedSaveEventsGameTelemetryV1ProtectedEventsPost(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'events'
      - 'game'
      - 'gametelemetry'
      - 'operations'
      - 'post'
      - 'protected'
      - 'save'
      - 'telemetry'
      - 'v1'

  'ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut@jv.gametelemetry.fun':
    id: 'ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut@jv.gametelemetry.fun'
    name: 'ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut'
    type: 'function'
    description: |-
      This endpoint requires valid JWT token.
      This endpoint does not require permission.

      This endpoint update player's total playtime in a specific game (AppId) from service's cache.
    arguments:
      'cookie':
        type: 'String'
        required: false
      'playtime':
        type: 'String'
        required: true
      'steamId':
        type: 'String'
        required: true
    return_type: 'PlayTimeResponse'
    imports:
      - 'import net.accelbyte.sdk.core.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.models.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.operations.gametelemetry_operations.*;'
      - 'import net.accelbyte.sdk.api.gametelemetry.wrappers.*;'
    files:
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/wrappers/GametelemetryOperations.java'
      - 'https://github.com/AccelByte/accelbyte-java-sdk/blob/main/src/main/java/net/accelbyte/sdk/api/gametelemetry/operations/gametelemetry_operations/ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut.java'
    example: |-
      try {
          final ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut operation = ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut.builder()
              .cookie(...)
              .build(
                  playtime,
                  steamId,
              );

          final GametelemetryOperations wrapper = new GametelemetryOperations(sdk);
          final PlayTimeResponse response = wrapper.protectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut(operation);
      }
      catch (HttpResponseException e) { /* Handle exceptions. */ }
      catch (Exception e)             { /* Handle exceptions. */ }
    tags:
      - 'game'
      - 'gametelemetry'
      - 'id'
      - 'ids'
      - 'operations'
      - 'playtime'
      - 'protected'
      - 'put'
      - 'steam'
      - 'telemetry'
      - 'update'
      - 'v1'
  # endregion functions